from datetime import date, datetime
import os

from sqlalchemy import select
from sqlalchemy.orm import Session
from .. import models
from ..auth.security import hash_password
from .ledger import log_action, recalculate_customer_ledger, recalculate_bank_ledger, recalculate_after_transaction


def seed_database(db: Session) -> None:
    # 1. Seed Operational & Administrator Accounts
    admin = db.scalar(select(models.User).where(models.User.email == "admin@brb.com"))
    if not admin:
        admin = models.User(
            name="Balam Bar Baran Admin",
            username="admin",
            email="admin@brb.com",
            password_hash="pbkdf2_sha256$0b0d56b777952d5ea33847708b335459$11485b9697768ffc967d6f35fbdbd9325d908ae84f6d43adfb6c4ea98e32324a",
            role="Admin",
            is_active=True,
        )
        db.add(admin)
        db.flush()

    default_user = db.scalar(select(models.User).where(models.User.email == "ahsan@sky.com"))
    if not default_user:
        default_user = models.User(
            name="Ahsan",
            username="ahsan",
            email="ahsan@sky.com",
            password_hash=hash_password("Qur78Ahs@@"),
            role="Admin",
            is_active=True,
        )
        db.add(default_user)
        db.flush()
    elif not default_user.username:
        default_user.username = "ahsan"
        db.flush()

    accountant = db.scalar(select(models.User).where(models.User.email == "accountant@skybanking.local"))
    if not accountant:
        accountant = models.User(
            name="General Accountant",
            username="accountant",
            email="accountant@skybanking.local",
            password_hash="pbkdf2_sha256$faa45d519d899578ca58e5834bc6909a$8888dbf3dbf9a46d3e18549da6667deedc194057ebfa2b6a5628548aeb7ac1d3",
            role="Accountant",
            is_active=True,
        )
        db.add(accountant)
        db.flush()

    balam_user = db.scalar(select(models.User).where(models.User.email == "balam@sky.com"))
    if not balam_user:
        balam_user = models.User(
            name="Balam Bar Baran",
            username="balam",
            email="balam@sky.com",
            password_hash="pbkdf2_sha256$f8ba639e7097ae4722c05badb88c6487$28a475360f24c29e570287d9f1fd7fd4f7df6c6cf0138c0a642dd8518e3b6f7a",
            role="Accountant",
            is_active=True,
        )
        db.add(balam_user)
        db.flush()

    # 2. Company Settings
    settings = db.scalar(select(models.Settings))
    if not settings:
        settings = models.Settings(
            company_name="Sky Ariana Group of Companies",
            logo_path="/app/backend/app/uploads/logo-343.png",
            address="Kandahar, Afghanistan",
            phone="+93 700 9393 65, +93 711 4355 29",
            email="transport@skyariana.com",
            receipt_footer="Official receipt generated by Sky Ariana Group of Companies.2026",
            default_currency="USD",
            receipt_prefix="TX",
            auto_backup=True,
            last_backup_at="2026-07-23 14:30:08",
            next_receipt_number=5,
        )
        db.add(settings)
        db.flush()
    else:
        settings.company_name = "Sky Ariana Group of Companies"
        settings.address = "Kandahar, Afghanistan"
        settings.phone = "+93 700 9393 65, +93 711 4355 29"
        settings.email = "transport@skyariana.com"
        settings.receipt_footer = "Official receipt generated by Sky Ariana Group of Companies.2026"
        db.flush()

    # 3. Seed Bank Accounts
    bank_defs = [
        {
            "bank_name": "OMAID AHSAN SARAPI",
            "account_name": "HAWALA TO ITAN",
            "account_number": "SKY-0012-8890-USD",
            "currency": "USD",
            "opening_balance": 25000,
            "current_balance": 40000,
        },
        {
            "bank_name": "Ghazanfar Bank",
            "account_name": "Company Account",
            "account_number": "4471-2200-AFN",
            "currency": "Afghani",
            "opening_balance": 880000,
            "current_balance": 880000,
        },
        {
            "bank_name": "Hawala Office",
            "account_name": "Dubai Hawala Desk",
            "account_number": "DXB-HWL-443",
            "currency": "Dirham",
            "opening_balance": 12000,
            "current_balance": 12000,
        },
        {
            "bank_name": "AIB Bank",
            "account_name": "Booking Account",
            "account_number": "1102-8890-USD",
            "currency": "USD",
            "opening_balance": 25000,
            "current_balance": 25000,
        },
    ]

    banks_by_account = {}
    for b_data in bank_defs:
        b_acc = db.scalar(select(models.BankAccount).where(models.BankAccount.account_number == b_data["account_number"]))
        if not b_acc:
            b_acc = models.BankAccount(**b_data)
            db.add(b_acc)
            db.flush()
        banks_by_account[b_data["account_number"]] = b_acc

    # 4. Seed Customers
    customer_defs = [
        {"name": "BALAM BAR BARAN", "phone": "+93 700 333 444", "notes": "Transport statement customer"},
        {"name": "شیر احمد", "phone": "+93 700 111 222", "notes": "Primary hawala customer"},
        {"name": "Ariana Balam Baran", "phone": "+93 700 333 444", "notes": "Transport statement customer"},
        {"name": "HAJI SHABIR AHMAD ALOKOZAY "},
        {"name": "HAJI SHABIR AHMAD ALOKOZAY"},
        {"name": "Balam Bar Baran"},
    ]

    customers_by_name = {}
    for c_data in customer_defs:
        c_obj = db.scalar(select(models.Customer).where(models.Customer.name == c_data["name"]))
        if not c_obj:
            c_obj = models.Customer(**c_data)
            db.add(c_obj)
            db.flush()
        customers_by_name[c_data["name"]] = c_obj

    # 5. Seed Real Transactions
    tx_defs = [
        {
            "receipt_no": "SKY-TX-01",
            "date": date(2026, 7, 23),
            "type": "Paid",
            "customer_id": customers_by_name["HAJI SHABIR AHMAD ALOKOZAY"].id,
            "company_name": "BALAM BAR BARAN",
            "subject": "EXPORTS ",
            "amount": 3784,
            "currency": "USD",
            "equivalent_amount": 700000000,
            "equivalent_currency": "Toman",
            "payment_method": "Hawala",
            "receiver_name": "Mrs Khanam Tokali Bolambar",
            "description": "۱/۵/۱۴۰۵\nنقد برایت جمع میشه\nتوسط امید احسان صرافی \nبه حساب عبدالمنان کرکیچ \n700,000,000/ تومان \n3784$ دالره \n@Mrs Khanam Tokali Bolambar\nحساب بلم بار باران\nد دالرو حساب",
            "status": "Completed",
            "created_by": admin.id,
        },
        {
            "receipt_no": "SKY-TX-002",
            "date": date(2026, 7, 25),
            "type": "Export",
            "customer_id": customers_by_name["Balam Bar Baran"].id,
            "company_name": "Balam Bar Baran",
            "subject": "exports -of containers",
            "amount": 15000,
            "currency": "USD",
            "equivalent_amount": 2797500000,
            "equivalent_currency": "Toman",
            "payment_method": "Hawala",
            "bank_account_id": banks_by_account["SKY-0012-8890-USD"].id,
            "receiver_name": "Mrs Khanam Tokali Bolambar",
            "description": "۳/۵/۱۴۰۵\nنقد برایت جمع میشه\nتوسط امید احسان صرافی \nبه حساب خانم تاجک \n2,797,500,000/ تومان\n15,000$ دالر ",
            "status": "Completed",
            "created_by": admin.id,
        },
    ]

    for t_data in tx_defs:
        existing_tx = db.scalar(select(models.Transaction).where(models.Transaction.receipt_no == t_data["receipt_no"]))
        if not existing_tx:
            tx = models.Transaction(**t_data)
            db.add(tx)
            db.flush()
            recalculate_after_transaction(db, tx)

    # 6. Recalculate Ledgers
    for cust in db.scalars(select(models.Customer)).all():
        recalculate_customer_ledger(db, cust.id)
    for b_acc in db.scalars(select(models.BankAccount)).all():
        recalculate_bank_ledger(db, b_acc.id)

    # 7. Audit Logs Seed
    if not db.scalar(select(models.AuditLog).limit(1)):
        audit_records = [
            {"user_id": admin.id, "action": "update", "table_name": "users", "record_id": 1, "description": "Changed password for admin@brb.com", "created_at": datetime(2026, 7, 13, 5, 48, 3)},
            {"user_id": admin.id, "action": "delete", "table_name": "customers", "record_id": 1, "description": "Deleted customer شیر احمد", "ip_address": "104.234.53.181", "device_info": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152.0.0.0 Safari/537.36", "created_at": datetime(2026, 7, 13, 14, 10, 34)},
            {"user_id": admin.id, "action": "update", "table_name": "customers", "record_id": 2, "description": "Updated customer BALAM BAR BARAN", "ip_address": "104.234.53.168", "device_info": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/152.0.0.0 Safari/537.36", "created_at": datetime(2026, 7, 13, 15, 27, 0)},
            {"user_id": admin.id, "action": "create", "table_name": "users", "record_id": 3, "description": "Created user balam@sky.com", "created_at": datetime(2026, 7, 14, 20, 35, 45)},
            {"user_id": admin.id, "action": "create", "table_name": "transactions", "record_id": 2, "description": "Added transaction SKY-TX-01", "ip_address": "45.146.54.168", "device_info": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/152.0.0.0 Safari/537.36", "created_at": datetime(2026, 7, 23, 12, 6, 51)},
            {"user_id": admin.id, "action": "update", "table_name": "bank_accounts", "record_id": 1, "description": "Updated bank account SKY-0012-8890-USD", "ip_address": "45.8.19.144", "device_info": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/152.0.0.0 Safari/537.36", "created_at": datetime(2026, 7, 23, 13, 58, 28)},
            {"user_id": admin.id, "action": "export", "table_name": "backup", "description": "Full database JSON backup exported", "ip_address": "45.8.19.146", "device_info": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/152.0.0.0 Safari/537.36", "created_at": datetime(2026, 7, 23, 14, 30, 8)},
            {"user_id": admin.id, "action": "create", "table_name": "transactions", "record_id": 4, "description": "Added transaction SKY-TX-002", "ip_address": "10.29.161.129", "device_info": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/152.0.0.0 Safari/537.36", "created_at": datetime(2026, 7, 25, 10, 42, 20)},
        ]
        for a_data in audit_records:
            log = models.AuditLog(**a_data)
            db.add(log)

    db.commit()
